
name: test-self-hosted-runner
on: push

jobs:
  smoke:
    runs-on: [self-hosted, linux]
    steps:
      - name: Smoke test
        run: |
          whoami
          hostname
          uname -a
          date
      - name: Create hello.txt
        run: |
          echo "hello from runner" > hello.txt
          pwd
          ls -la
          cat hello.txt
