- run: echo "hello from runner" > hello.txt
name: test-self-hosted-runner
on: push

jobs:
  smoke:
    runs-on: [self-hosted, linux]
    steps:
      - name: Smoke test
        run: |
          whoami
          hostname
          uname -a
          date
